spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    # The URl must be copied from the CLUSTER
    url: jdbc:postgresql://TODO:5432/codehunters_user_events
    username: ${DB_USERNAME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true