apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: events-service
  namespace: codehunters
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: events-service
  endpoints:
    - port: http
      path: /actuator/prometheus