# Source: https://dev.to/aws-builders/working-with-eks-using-iam-and-native-k8s-service-accounts-to-access-aws-s3-3e20
# Source: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-events-service
  namespace: codehunters
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::584279960914:role/CodeHuntersEventsServiceEKSRole
    eks.amazonaws.com/sts-regional-endpoints: "true"
