apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-events-service
  namespace: czirjak
  labels:
    release: kube-prometheus # kubectl get prometheus -o yaml -n monitoring
spec:
  selector:
    matchLabels:
      app: service-events-service # Service selector
  endpoints:
    - port: http
      path: '/actuator/prometheus'
      interval: 10s
      honorLabels: true