apiVersion: apps/v1
kind: ???
metadata:
  name: events-service
  namespace: ???
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      serviceAccountName: service-account-events-service
      containers:
        - name: events-service
          imagePullPolicy: Always
          image: 584279960914.dkr.ecr.eu-central-1.amazonaws.com/eventsserviceecr:???
          ports:
            - containerPort: ???
          env:
            - name: CONFIG_ENV
              value: " ??? "
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: " ??? "
              cpu: " ??? "
          livenessProbe:
            httpGet:
              port: 8080
              path: ???
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: ???
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
