apiVersion: v1
kind: ???
metadata:
  name: service-events-service
  namespace: ???
spec:
  selector:
    app: events-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: ???
  type: ClusterIP