apiVersion: v1
kind: Service
metadata:
  name: service-events-service
  namespace: czirjak
  labels:
    app: service-events-service
spec:
  selector:
    app: events-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP