apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider-events-service
  namespace: codehunters
spec:
  provider: aws
  parameters:
    region: eu-central-1
    objects: |
      - objectName: "codehunters-aurora-secrets-v8"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"            
          - path: "password"
            objectAlias: "password"
  secretObjects:
    - secretName: database-credentials
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password